### ISSUE TITLE
Oneindige loop

### ISSUE THREAD

**Issue by raymondnijssen** [Uijtdehaag/Verkeersborden#1]
Het script draait oneindig door, omdat de laatste xml maar 1 item bevat, waarvan het tijdstip wordt gebruikt om de volgende xml op te vragen. Die bevat dan weer dezelfde xml, enz, enz, enz

Omdat de data niet tussentijds wordt opgeslagen als csv, kun je het script alleen maar afbreken zonder enig resultaat te hebben.

**Comment by Uijtdehaag** [comment]
Mooie verbetering. Toeval dat het bij mij wel werkte en ik het niet had opgemerkt.
